### ISSUE TITLE
ONBOARD_CONTROLLER_HDMI value not well retreived which leads to an Error during boot

### ISSUE THREAD

**Issue by DrBuns3n** [Vilikt/PiBoy-Configurator#1]
Experiencing an error during boot with PiBoy-Configurator: 
![IMG_1189](https://user-images.githubusercontent.com/36809959/101690825-b0890180-3a22-11eb-8c11-ae51d0939070.PNG)

**Comment by Vilikt** [comment]
It seems that the value of the onboard_controller_in_hdmi is not well initialize. 
If it's not present in piboy.cfg it should be automatically created.

Could you share your piboy.cfg please ?

**Comment by Vilikt** [comment]
Forger my last message. I fixed the problem.
Just perform update and let me know if all is OK for you.

**Comment by DrBuns3n** [comment]
The error during boot is different now, but there's still an error. 
![IMG_1192](https://user-images.githubusercontent.com/36809959/101700954-d0282600-3a32-11eb-945b-2a306ebeac9e.jpg)

**Comment by Vilikt** [comment]
Sorry for the wait and the inconvenience.
I corrected, can you test on your side?

**Comment by Vilikt** [comment]
Please check in piboy.cfg if the "onboard_controller_hdmi" node exists.

If not -> no problem.

If so, verify that the value of is "yes" or "no" and not "1" or "0".

**Comment by DrBuns3n** [comment]
Current piboy.cfg after 1.3.2 update:
```<?xml version='1.0' encoding='utf-8'?>
<config>
  <overscan_value>0</overscan_value>
  <overscan_enable>no</overscan_enable>
  <bt_always_enable_lcd>undefined</bt_always_enable_lcd>
  <wifi_always_enable_lcd>undefined</wifi_always_enable_lcd>
  <bt_always_enable_hdmi>undefined</bt_always_enable_hdmi>
  <wifi_always_enable_hdmi>undefined</wifi_always_enable_hdmi>
  <onboard_controller_hdmi>yes</onboard_controller_hdmi>
  <theme_tv />
  <theme_lcd />
  <bt_enable />
  <wifi_enable />
  <overlay_style>grid</overlay_style>
</config>```

**Comment by Vilikt** [comment]
I just commited some corrections. I hope your case should be OK now.

**Comment by DrBuns3n** [comment]
Not seeing any errors at boot now, thanks for the update!

**Comment by Vilikt** [comment]
No problem
